sass:
  sass_dir: assets/css

collections:
  projects:
    output: true

defaults:
  - scope:
      path: "_posts/blog/"
    values:
      permalink: /blog/:year/:title/
      layout: "post"
  - scope:
      path: "_posts/notes/"
    values:
      category: "notes"
      layout: "note"
      permalink: /notes/:year/:title/
  - scope:
      type: "projects"
    values:
      layout: "project"
      permalink: /portfolio/:title/

